format_version: 2
pipelines:
  Build_And_Publish_Image:
    group: GocdAgents
    materials:
      git:
        git: https://github.com/christi4n/gocd-agents.git
        branch: develop
    stages:
      - Build_And_Publish:
        jobs:
          Build_Image:
            tasks:
              - exec:
                command: /bin/sh
                arguments:
                  - "ls"
              - exec:
                command: /bin/sh
                arguments:
                  - ./scripts/commit/build.sh