format_version: 2
pipelines:
  Backend_CommitPhase:
    group: GocdAgents
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    materials:
      backend:
        git: https://github.com/christi4n/gocd-agents.git
        branch: develop
        shallow_clone: true
        auto_update: true
    environment_variables:
      DOCKERHUB_USERNAME: amarissuisse
      IMAGE_NAME: gocd-agent-java8
    stages:
      - Build:
          clean_workspace: true
          jobs:
            Build:
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/sh
                    arguments:
                    - ./scripts/commit/build.sh
      - Unit_Tests:
          jobs:
            Run_Unit_Tests:
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/sh
                    arguments:
                    - ./scripts/commit/unit-test.sh
      - Build_Docker_Image:
          jobs:
            Build_Image:
              elastic_profile_id: demo-app
              tasks:
                - exec:
                  command: echo
                  arguments:
                    - "$DOCKERHUB_USERNAME"
                - exec:
                  command: echo
                  arguments:
                    - "$IMAGE_NAME"
                - exec:
                  run_if: passed
                  command: /bin/sh
                  arguments:
                    - ./scripts/commit/docker-build.sh
                    - "${DOCKERHUB_USERNAME}"
                    - "${IMAGE_NAME}"
                - exec:
                  run_if: passed
                  command: /bin/sh
                  arguments:
                    - ./scripts/commit/docker-tag.sh
      - Push_To_Registry:
          jobs:
            Push:
              elastic_profile_id: demo-app
              tasks:
                - exec:
                    run_if: passed
                    command: /bin/sh
                    arguments:
                    - ./scripts/commit/docker-push.sh