format_version: 3
pipelines:
  build_and_publish_image:
    group: GOCD-Agents
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    materials:
      SourceCodeRepo:
        git: https://github.com/christi4n/gocd-agents.git
        shallow_clone: false
        auto_update: true
        branch: master
        name: SourceCodeRepo
    environment_variables:
      DOCKERHUB_USERNAME: "amarissuisse"
      IMAGE_NAME: "gocd-agent-java8"
    stages:
      - build_and_publish_image:
          clean_workspace: true
          fetch_materials: false
          keep_artifacts: true
          approval:
            type: success
          jobs:
            build_image:
              timeout: 0
              elastic_profile:
                name: k8-cluster-profile
                elastic_profile_id: k8-cluster-profile
              tasks:
                - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - docker build -t $DOCKERHUB_USERNAME/gocd-agent-java8:$GO_PIPELINE_LABEL . -f ../java/v8/Dockerfile.agent
                  run_if: passed