format_version: 3

pipelines:
  build_and_publish_image:
    group: GOCD-Agents
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    materials:
      SourceCodeRepo:
        git: https://github.com/christi4n/gocd-agents.git
        shallow_clone: true
        auto_update: true
        branch: master
    environment_variables:
      DOCKERHUB_USERNAME: "amarissuisse"
      IMAGE_NAME: "gocd-agent-java8"
    stages:
    - build_and_publish_image:
      clean_workspace: false
      fetch_materials: false
      keep_artifacts: false
      approval:
        type: success
      jobs:
        build_image:
          timeout: 0
          elastic_profile_id: demo-app
          artifacts:
          - external:
            id: gocd-agent-java8
            store_id: docker_hub
            configuration:
              option:
                Image: ${DOCKERHUB_USERNAME}/${IMAGE_NAME}
                Tag: ${GO_PIPELINE_LABEL}
          
          tasks:
            - exec:
              run_if: passed
              command: bash
              arguments:
              - ./scripts/commit/build.sh