format_version: 3
pipelines:
  Build_And_Publish_Image:
    group: GocdAgents
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: 1
    materials:
      git:
        git: https://github.com/christi4n/gocd-agents.git
        shallow_clone: true
        auto_update: true
        branch: master
    environment_variables:
      DOCKERHUB_USERNAME: "amarissuisse"
      IMAGE_NAME: "gocd-agent-java8"
    stages:
      - Build_And_Publish:
        clean_workspace: false
        fetch_materials: true
        keep_artifacts: false
        approval:
          type: success
        jobs:
          Build_Image:
            tasks:
              - exec:
                command: /bin/sh
                arguments:
                - "ls"
              - exec:
                run_if: passed
                command: /bin/sh
                arguments:
                - "./scripts/commit/build.sh"